src = ["src/git_secret_scanner"]

select = ["ALL"]
ignore = [
    "BLE",     # flake8-blind-except
    "C90",     # mccabe
    "D",       # pydocstyle
    "EXE",     # flake8-executable
    "FA100",   # flake8-future-annotations:future-rewritable-type-annotation
    "FA102",   # flake8-future-annotations:future-required-type-annotation
    "FBT",     # flake8-boolean-trap
    "FIX",     # flake8-fixme
    "I001",    # isort:unsorted-imports
    "PLR0913", # Pylint:too-many-arguments
    "PLR1714", # Pylint:repeated-equality-comparison-target
    "PLW1510", # Pylint:subprocess-run-without-check
    "TCH",     # flake8-type-checking
    "TD",      # flake8-todos
]

line-length = 120


[flake8-quotes]
inline-quotes = "single"
multiline-quotes = "single"
