name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Golang
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Get ldflags env values
        run: |
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=git-secret-scanner@${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_PAT: ${{ secrets.HOMEBREW_PAT }}
        with:
          version: "~> 2"
          args: release --clean
  
  build-and-push:
    name: Build and Push

    uses: ./.github/workflows/build-and-push.yaml
